name: Functional Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    name: Run Functional Tests
    env:
      TERM: xterm-256color
    permissions:
      checks: write
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create results directories
        run: |
          mkdir -p results/functional
          mkdir -p results/api
          mkdir -p results/junit
        
      - name: Run E2E tests with Mochawesome reporter
        run: npx cypress run --config-file cypress.config.e2e.ts --spec "cypress/e2e/*.cy.ts" --browser chrome --reporter mochawesome --reporter-options reportDir=results/functional,overwrite=false,html=false,json=true
        
      - name: Run E2E tests with JUnit reporter
        run: npx cypress run --config-file cypress.config.e2e.ts --spec "cypress/e2e/*.cy.ts" --browser chrome --reporter mocha-junit-reporter --reporter-options mochaFile=results/junit/e2e-test-results-[hash].xml,testsuitesTitle='Cypress E2E Tests',toConsole=true
        
      - name: Run API tests with Mochawesome reporter
        run: npx cypress run --config-file cypress.config.api.ts --spec "cypress/api/**/*.cy.ts" --browser chrome --reporter mochawesome --reporter-options reportDir=results/api,overwrite=false,html=false,json=true
        
      - name: Run API tests with JUnit reporter
        run: npx cypress run --config-file cypress.config.api.ts --spec "cypress/api/**/*.cy.ts" --browser chrome --reporter mocha-junit-reporter --reporter-options mochaFile=results/junit/api-test-results-[hash].xml,testsuitesTitle='Cypress API Tests',toConsole=true
        
      - name: Generate E2E test report
        run: npm run report:functional
        
      - name: Generate API test report
        run: npm run report:api
        
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            results/functional/
            cypress/videos/functional/
            cypress/screenshots/functional/
          retention-days: 30
          
      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: |
            results/api/
            cypress/videos/api/
            cypress/screenshots/api/
          retention-days: 30
          
      - name: Upload JUnit Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: results/junit/
          
      - name: Publish E2E Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress E2E JUnit Report
          path: results/junit/e2e-test-results-*.xml
          reporter: java-junit
          fail-on-error: false
          
      - name: Publish API Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress API JUnit Report
          path: results/junit/api-test-results-*.xml
          reporter: java-junit
          fail-on-error: false